# Generated by Django 3.0.8 on 2020-11-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_model',
            name='category',
            field=models.CharField(choices=[('item 1', 'item 1'), ('item 2', 'item 2'), ('item 3', 'item 3')], default='it1', max_length=6),
        ),
    ]
