# Generated by Django 3.0.8 on 2020-11-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker_app', '0002_auto_20201109_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_model',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
