# Generated by Django 3.0.8 on 2020-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker_app', '0004_expenses_model_is_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_model',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
    ]
