# Generated by Django 3.0.8 on 2020-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker_app', '0005_auto_20201112_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_model',
            name='category',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='expenses_model',
            name='is_expense',
            field=models.CharField(max_length=7),
        ),
    ]
