# Generated by Django 3.0.8 on 2020-11-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker_app', '0007_expense_category_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense_category_model',
            old_name='category',
            new_name='category_item',
        ),
    ]
