# Generated by Django 3.0.8 on 2020-12-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker_app', '0008_auto_20201119_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses_model',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
