# Generated by Django 3.0.8 on 2021-01-15 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_details_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_name', models.CharField(max_length=100)),
                ('watch_providers', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('movie_overview', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote_system_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_key', models.CharField(max_length=4)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
