# Generated by Django 3.0.8 on 2020-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200810_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='urltag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
