# Generated by Django 3.0.8 on 2021-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201203_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='s3_image_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
