# Generated by Django 3.0.8 on 2020-08-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('CP', 'Completed')], default=('NS', 'Not Started'), max_length=2)),
            ],
        ),
    ]
