# Generated by Django 3.0.8 on 2020-08-12 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20200812_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
