# Generated by Django 3.0.8 on 2020-08-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todo_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='status',
        ),
        migrations.AddField(
            model_name='todo_list',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='list_item',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
