# Generated by Django 3.0.8 on 2020-09-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20200819_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='list_item',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
