# Generated by Django 3.0.8 on 2020-09-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20200914_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='date',
        ),
    ]
